windowrule = match:title (<floating>),                   float on
windowrule = match:title (<floating>),                   size 80% 80%
windowrule = match:class ^(blueman-manager)$,            float on
windowrule = match:class ^(blueman-manager)$,            size 80% 80%
windowrule = match:class ^(nm-connection-editor)$,       float on
windowrule = match:class ^(nm-connection-editor)$,       size 80% 80%
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, size 80% 80%
windowrule = match:class ^(org.pipewire.Helvum)$,        float on
windowrule = match:class ^(org.pipewire.Helvum)$,        size 80% 80%

# Krita
windowrule = match:title ^(Saving As — Krita)$, center 1
windowrule = match:title ^(Saving As — Krita)$, size 70% 70%

# Ardour
windowrule = match:class ^(Ardour-[\d+\.]+)$,    match:title ^(Session Setup)$,                center 1
windowrule = match:class ^(Ardour(-[\d+\.]+)?)$, match:title ^.*(Helm|Calf|ACE|Select|SF2).*$, center 1
windowrule = match:class ^(Ardour-[\d+\.]+)$,    match:title ^(Select|SF2).*$,                 size 50% 50%
