theme = "dark-lynx"

[editor]
bufferline = "multiple"
line-number = "relative"
scrolloff = 8
rulers = []
file-picker.hidden = false
color-modes = true

auto-completion = true
completion-trigger-len = 1
idle-timeout = 0
auto-format = true

[editor.indent-guides]
render = true
character = "▏"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = [
  # "file-base-name",
  # "separator",
  # "selections",
  # "position-percentage",
  # "total-line-numbers"
]
right = ["diagnostics", "file-encoding", "file-type", "separator", "position"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
Y = "yank_joined"

[keys.normal.ret]
w = ":w"
W = ":w!"
q = ":q"
Q = ":q!"
x = ":bc"
X = ":bc!"
f = ":format"
r = ":reload-all"

c = ":config-reload"
C = ":config-open"
A-c = ":o .helix/config.toml"
s = ":o ~/.config/helix/themes/dark-lynx.toml"
l = ":lsp-restart"
L = ":o ~/.config/helix/languages.toml"
A-l = ":o .helix/languages.toml"

[keys.normal."+"]
b = ":sh cargo build"
B = ":sh cargo build --release"
r = ":sh cargo run"
t = ":sh cargo test"
T = ":sh cargo test -- --nocapture"
d = ":sh cargo doc --open"
f = ":sh leptosfmt ."

[keys.normal."#"]
s = ":set whitespace.render all"
S = ":set whitespace.render none"
r = ":set rulers [80]"
R = ":set rulers []"
f = ":toggle auto-format"
g = ":toggle indent-guides.render"
h = ":toggle lsp.display-inlay-hints"
c = ":toggle color-modes"
w = ":toggle soft-wrap.enable"

[keys.insert]
C-h = "move_char_left"
C-l = "move_char_right"
C-w = "move_next_word_start"
C-e = "move_next_word_end"
C-b = "move_prev_word_start"
