[language-server.rust-analyzer.config]
cargo = { allFeatures = true }
procMacro = { ignored = { leptos_macro = [
    "server"
] } }

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]


[[language]]
name = "rust"


[[language]]
name = "css"
auto-format = false


[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-lsp"]
auto-format = false
